language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t nspoonts/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nspoonts/docker-react npm run test